### ISSUE TITLE
live-code-preview doesn't bring sass styles

### ISSUE THREAD

**Issue by leonardofaria** [primer/doctocat#101]
Howdy

First of all, I am stoked with doctocat. We are moving from storybook at Thinkific and your theme is so cool. Never worked with Gatsby before and it has been a great developer experience.

We have a component library in React. Our components use SASS. I am trying different things here with the `jsx live` and I am not sure if this use case is mapped:

I have created a live-code-scope.js following your docs:
```js
import Badge from '../../components/Badge';
export default { Badge };
```

In my badge.mdx file I have:
```jsx live
<Badge type="primary">Primary</Badge>
```

The output of the code will be:
```html
<span class="badge badge--primary">Primary</span>
```
...but the styles are not there.

Tried a different approach: added an import in my mdx file (and the gatsby-plugin-sass plugin). This time the CSS works fine inside the mdx file, but not inside the `jsx live` block (reference error as covered in your docs). In details:

```mdx
import Badge from 'src/components/Badge'
<Badge type="primary">Primary</Badge>

jsx
<Badge type="primary">Primary</Badge>
```

Any ideas of what is going on here? 

Thanks and keep being awesome

**Comment by emplums** [comment]
Hey @leonardofaria! Thanks! :) Unfortunately, we are intentionally leaving out CSS that's included in the global scope of the page within our live preview editors - this is because some of the global CSS included in our markdown styles interferes with some of the content we show in our live editors. We do this by using iframes for all of our live editors.

What we do for the https://primer.style/css docs is shadow the `live-preview-wrapper.js` component, and include the stylesheet there: https://github.com/primer/css/blob/master/docs/src/%40primer/gatsby-theme-doctocat/components/live-preview-wrapper.js

There's a bit about component shadowing in our docs using the `Hero` component as an example here: https://github.com/primer/css/blob/master/docs/src/%40primer/gatsby-theme-doctocat/components/live-preview-wrapper.js but basically all you need to do is create a component in the same path location as where that component lives in doctocat. So for the live preview wrapper you would need to put it in  `docs/src/@primer/gatsby-theme-doctocat/components/live-preview-wrapper.js`

Let me know if that works! ✨

**Comment by colebemis** [comment]
We also have some docs on `live-preview-wrapper.js` here: https://primer.style/doctocat/usage/live-code#global-styles

**Comment by leonardofaria** [comment]
Thanks @emplums and @colebemis <3 

Last Friday I started shadowing a few components (header, sidebar) and it works like a charm :) 
I also customized the `live-preview-wrapper.js` to inject a CSS compiled file (like https://unpkg.com/primer/build/build.css)

Since you are here, do you have any tips for using tabs inside your docs?

Here is my case: for a Badge component, we have a CSS implementation and a React component. I know that Primer has two different urls for components (ex. Avatar) but we are looking for something like Polaris: https://polaris.shopify.com/components/images-and-icons/badge

Cheers

**Comment by emplums** [comment]
Hey @leonardofaria - we don't currently have any UI built out for that. But you could probably shadow [layout.js](https://github.com/primer/doctocat/blob/master/theme/src/components/layout.js) to make it - or fork the theme! 😸
