### ISSUE TITLE
Table of Contents Feedback

### ISSUE THREAD

**Issue by emplums** [primer/doctocat#137]
I noticed that for long tables of contents scrollbars show up - could we remove these?

![image](https://user-images.githubusercontent.com/8960591/78827785-8913fd80-7998-11ea-8a0d-64df10f18620.png)

I also wonder if the TOC should line up with the title instead of the first paragraph under the title? https://share.getcloudapp.com/RBuveZw4

 the live editors now are feeling a little narrow. Would it make sense to remove some of the padding to the left of the main content area to allow the live editors a bit more space? https://share.getcloudapp.com/NQuDLjed

related: the copy button in live editors overlays the text inside the editor. This was always happening but is more noticable now that the editors are more narrow. Could we make it so that the copy button never overlaps the code? https://share.getcloudapp.com/4guyweyG

**Comment by broccolini** [comment]
Quick design feedback:

<img width="312" alt="Screen Shot 2020-04-10 at 12 01 26 PM" src="https://user-images.githubusercontent.com/334891/79005642-564b4000-7b25-11ea-8bc5-33426ec3bc4a.png">

- It doesn't seem to be lined up with anything vertically, and generally seems like odd positioning
- It seems too close to the content, perhaps should be flush right, or in a box or something so doesn't look so floaty
- It also looks like we've made the page width smaller which I think is a mistake, we should make it wider if we put in the same container as the content lets make it wider to be the same width as before.

<img width="340" alt="Screen Shot 2020-04-10 at 12 08 22 PM" src="https://user-images.githubusercontent.com/334891/79005632-4fbcc880-7b25-11ea-817b-4871df1f7df7.png">

Mobile also needs some work. The Chevron should be facing down, same as in the global mobile nav. Something about this just feels off too, maybe resolved by style updates to desktop version if you add a box, or maybe just needs to be blue or something.

**Comment by yaili** [comment]
Some thoughts:

- I understand the position of the ToC aligned with the top of the first paragraph, as that's where it moves to in small screen, but I agree it would look better if we align with the page title
- Could we make the ToC text 14px instead? I think that would clarify the hierarchy/importance of the ToC in relation to the main content, and it may help with creating visual distance from the main content 
- I agree with the suggestion to make the page width wider so the main content has the same width as before
- Should we revert to the caret instead of chevron, in small screen?
- Can we add an indicator of where in the page we are? In the designs (see 🖼⬇️) I had an orange indicator, but happy with something else if it's easier/more in line with existing examples 

<img width="1438" alt="16  Discreet annotation w background, sidebar references" src="https://user-images.githubusercontent.com/223966/79569064-df76ef80-80ae-11ea-80eb-f17b404c029b.png">

**Comment by colebemis** [comment]
Closed by #166
