### ISSUE TITLE
Headers in left-side navigation don't have any link affordances

### ISSUE THREAD

**Issue by BinaryMuse** [primer/doctocat#140]
I learned today that the headings in the left-side nav can be clicked.

![image](https://user-images.githubusercontent.com/189606/80526506-b32d5f80-8947-11ea-911e-2083a92361a2.png)

If you don't casually roll over one of these, I think it's pretty difficult to know it's a link, as there are none of the standard hints that the element is clickable.

On Primer Components, we're considering simply removing those links and make the pages they link to more visible in the navigation: https://github.com/primer/components/pull/786

**Comment by yaili** [comment]
I'm not sure [this](https://github.com/primer/components/pull/786) solution would work across the board, as in a bunch of places we have overview pages for the sections (granted, the content in them could be better, but that's the plan). 

Some ideas:
- Something like what [Material](https://material.io/design) does could work, as the headings are not clickable at all
- Making sure the current headings are mainly overviews/directories for the sections, rather than adding new, important content ([issue](https://github.com/primer/doctocat/issues/121))
