### ISSUE TITLE
Image handling

### ISSUE THREAD

**Issue by superbryntendo** [primer/doctocat#162]
@emplums and I had a discussion today about how to handle images in doctocat because there are a couple of different ways we can handle images in Gatsby.

The current solution (storing images on a CDN and then referencing them) is fine, but not very efficient and the internal process is kinda hacky.

Perhaps the most obvious solution with Gatsby would be to use gatsby-image, but that has some fairly technical requirements that may be hard to work with for non-technical users.

One middle-ground alternative (h/t to @ampinsk), would be to import images into the mdx document, but this gives limited control and doesn't really optimize the images themselves.

**Comment by superbryntendo** [comment]
I think this plugin would actually give us standard markdown usage of images via relative paths: https://www.gatsbyjs.org/packages/gatsby-remark-images/

**Comment by emplums** [comment]
Clarification (just in case anyone finds this looking for how to use images in Doctocat) - the current solution for handling images can be either storing images on a CDN and then referencing the URL, or having an images folder in your gatsby project and importing the image via relative path. Both work fine and IMO are not hacky.

I do agree it would be great to have some optimization of images, but want to be careful we don't over engineer this/make it too technical for non-coders to contribute easily to documentation. The remark package seems reasonable if we find that users prefer to include images via markdown instead of simple `img` tags in HTML/mdx. If we do decide to go with gatsby-remark-images I would like this to be set up by default in the template repo's gatsby config and make sure that we have thorough documentation on how to get started with it if you're just installing the theme via the gatsby CLI.

**Comment by emplums** [comment]
friction point: it looks like whenever you change the name of a file in the `images/` folder, you have to delete the gatsby cache/rebuild
