### ISSUE TITLE
Showing CLI examples

### ISSUE THREAD

**Issue by ampinsk** [primer/doctocat#163]
Right now, we're showing CLI/Terminal examples using images, but it would be nice to have a solution that allowed for copy/pasting.

Ideas we discussed: 
- A "dark theme" version of the current codeblocks
- Leveraging syntax highlighting in some way to automate colorizing examples

**Comment by colebemis** [comment]
We can definitely change the syntax highlighting of code examples to a dark theme when the language is set to `shell`. For example, a code example written like this:

````
```shell
npm run develop
```
````

... would render like this:

![image](https://user-images.githubusercontent.com/4608155/91758536-08db7800-eb85-11ea-94b7-dc498d0d8a96.png)


... instead of like this:

![image](https://user-images.githubusercontent.com/4608155/91758414-d762ac80-eb84-11ea-9b7f-2ab7a362f284.png)

---

Correctly rendering the font-weight and colors in examples likes would be more difficult to implement. We'd likely have to introduce new syntax to allow you to indicate what words should be rendered in different colors and font weights.

![image](https://user-images.githubusercontent.com/4608155/91758762-5f48b680-eb85-11ea-8cc5-666d2eb47e44.png)
