### ISSUE TITLE
Doctocat User Feedback

### ISSUE THREAD

**Issue by emplums** [primer/doctocat#55]
- [ ] Migrating to Doctocat

I think we should have a specific section for migration to using Doctocat from another docs framework. This would generally mean documentation on using Doctocat inside of another repository. This was hinted at a bit in the docs but was a little hard to find/follow.

- [ ] [https://primer.style/doctocat/getting-started/gatsby-cli](https://primer.style/doctocat/getting-started/gatsby-cli)

It's not clear in these docs whether `my-site` is referring to the root name of your site, or the name of the folder that your docs live in

- [ ] `If you want to create a new site in an existing repository, be sure to run the gatsby new command from within that repository.`

This doesn't make it clear what arguments I should run with gatsby new if i have an existing repository, and where in that repo I should run it. Let's change this code snippet to the full command.

- [ ] I also need to run `npm i` after running the `gatsby new ...` command, lets make sure to add this to the docs

- [ ] https://primer.style/doctocat/getting-started/gatsby-cli

This doc should go through all the steps of setting up a site, similar to the `Getting Started` doc

- [ ] Let's be clear that you can name your site folder anything you'd like. We can provide naming guidance here if necessary.

- [ ] We need to mention that the `content` folder needs to be named `content` for Reasons.

- [ ] Let's add docs on where to put local components if you need to build them and how to import them and use them in an MDX - write this for the audience of people who might not have a ton of React experience

- [ ] 404 page missing

- [ ] Clicking on an item while scrolled down in the sidenav scrolls back up when the page changes, which is kind of annoying if you are clicking through items in the sidenav one by one

- [ ] Ran into some issues with the template putting a `now.json` in the docs folder, but needing to actually have it in the root. This has got me thinking that it is kind of confusing to have two pretty different ways of setting up a Doctocat site - within a subdirectory, or in the root and how different those setups end up being 🤔 I'm not sure what the solution is because I know this is due to limitations with template repos but wanted to mention it.

**Comment by colebemis** [comment]
@ashygee feedback:
- Improve Gatsby CLI documentation. Felt incomplete.
- Too much jargon. Use simpler words or define terms (e.g. shadowing).
- Add more diagrams to illustrate what's happening.
- It wasn't clear that `nav.yml` needed to be changed to update navigation. Maybe add a diagram.
- Add a section about creating and using local components.
- Add more documentation about writing MDX (specifically import statements).
- Add lint script to package.json in the template
- `DS_Store` should be git ignored in template
- Add built-in component for rendering step-by-step guides with images
- Text-only Do/Don't component
- Make table of contents look nicer

@emilybrick feedback:
- Add more built-in components like Do/Don't and Caption.
- Syntax error would crash the whole dev server.
- Dev server caused terminal to freeze.

@emplums feedback:
- `.cache` directory should be git ignored
- Sometimes `.cache` causes errors even when the errors where fixed in the code.
